name: Tennis Court Booking

on:
  workflow_dispatch:
    inputs:
      target_day:
        description: 'Target Day'
        default: 'Saturday'
        required: true
      time_slot1:
        description: 'Time Slot 1'
        default: '14:00:00'
        required: true
      courts:
        description: 'Courts (comma-separated)'
        default: 'D,C'
        required: true

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull anton665/tennis-bot:single

      - name: Run booking script from Docker image (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          docker run --rm \
            -e TARGET_DAY="${{ github.event.inputs.target_day }}" \
            -e TIME_SLOT1="${{ github.event.inputs.time_slot1 }}" \
            -e COURTS="${{ github.event.inputs.courts }}" \
            -e FULL_NAME="${{ secrets.FULL_NAME }}" \
            -e EMAIL="${{ secrets.EMAIL }}" \
            -e PHONE_NUMBER="${{ secrets.PHONE_NUMBER }}" \
            -e CCODE="${{ secrets.CCODE }}" \
            -e TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            -e TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}" \
            anton665/tennis-bot:single
