name: Tennis Court Booking

on:
  schedule:
    - cron: '1 0 * * 5'  # Every Friday 08:01 AM PH time (00:01 UTC)
  workflow_dispatch:
    inputs:
      target_day:
        description: 'Target Day'
        default: 'Saturday'
        required: true
      time_slot1:
        description: 'Time Slot 1'
        default: '14:00:00'
        required: true
      time_slot2:
        description: 'Time Slot 2'
        default: '15:00:00'
        required: true
      courts:
        description: 'Courts (comma-separated)'
        default: 'D,C'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        env:
          TARGET_DAY: ${{ github.event.inputs.target_day }}
          TIME_SLOT1: ${{ github.event.inputs.time_slot1 }}
          TIME_SLOT2: ${{ github.event.inputs.time_slot2 }}
          COURTS: ${{ github.event.inputs.courts }}
          FULL_NAME: ${{ secrets.FULL_NAME }}
          EMAIL: ${{ secrets.EMAIL }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          CCODE: ${{ secrets.CCODE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tennis_consecutive_slots_booking.py

      - name: Run script (scheduled)
        if: github.event_name == 'schedule'
        env:
          FULL_NAME: ${{ secrets.FULL_NAME }}
          EMAIL: ${{ secrets.EMAIL }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          CCODE: ${{ secrets.CCODE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python tennis_consecutive_slots_booking.py
